INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('3', '1', '1', '3', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('5', '1', '2', '2', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('8', '1', '3', '30', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('10', '1', '10', '1', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('12', '4', '6', '1', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('15', '3', '5', '15', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('17', '5', '3', '20', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('19', '6', '10', '1', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('20', '7', '4', '1', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('23', '8', '10', '15', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('25', '9', '10', '10', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('28', '10', '10', '50', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('30', '6', '10', '3', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('33', '6', '10', '5', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('34', '2', '7', '15', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('36', '11', '9', '12', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('38', '1', '8', '100', now());
INSERT INTO transaksi (`id_transaksi`,`id_pelanggan`, `id_produk`,`jumlah_produk`, `tanggal_transaksi`)
VALUES ('40', '12', '10', '14', now());

SELECT * FROM transaksi
